image: gradle:7.3.3

pipelines:
  pull-requests:
    '**':
      - step:
          name: Build and Test
          script:
            - cd backend
            - bash gradlew clean build
  branches:
    'master':
      - step:
          name: Build and Test
          script:
            - cd backend
            - bash gradlew clean build